version: "3.9"

services:
  bot:
    build: .
    container_name: aldazcheck_bot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_AUTH_TOKEN=tu_token_aqui
    restart: unless-stopped
